# Generated by Django 3.2.8 on 2022-01-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blue', '0002_form_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=1000),
        ),
    ]
