# Generated by Django 3.2.8 on 2022-01-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blue', '0003_form_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='address',
            field=models.TextField(default='abcd'),
        ),
        migrations.AddField(
            model_name='form',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
