# Generated by Django 3.2.8 on 2022-01-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blue', '0004_auto_20220112_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='xiipercentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='form',
            name='xpercentage',
            field=models.IntegerField(default=0),
        ),
    ]
