# Generated by Django 3.2.8 on 2022-01-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blue', '0005_auto_20220112_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='training',
            field=models.CharField(default='training', max_length=1000),
        ),
    ]
