# Generated by Django 3.2.8 on 2022-01-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blue', '0006_form_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='city',
            field=models.CharField(default='city', max_length=1000),
        ),
    ]
