# Generated by Django 3.2.8 on 2022-01-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blue', '0007_form_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='title',
        ),
    ]
